morpho-org/sdks

packages/blue-sdk/package.json, packages/blue-sdk/src/addresses.ts
new crv token wrapping was missing
=> feat(blue-sdk): add missing crv wrapping

packages/blue-api-sdk/src/types.ts
[API PR](https://github.com/morpho-org/morpho-blue-api/pull/488)
=> feat(blue-api-sdk): bump types

packages/blue-api-sdk/src/converter.ts
Same as https://github.com/morpho-org/sdks/pull/182 but on main
=> fix(blue-api-sdk): fix market apys computation

packages/blue-api-sdk/src/warnings.ts
Needed for [INTER-1774](https://linear.app/morpho-labs/issue/INTER-1774/v2-new-warning)
=> feat(api-sdk): add warning types

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/test.yml
- for security considerations, we should freeze the lockfile
=> fix(ci): freeze pnpm lockfile

packages/blue-sdk-ethers/src/fetch/Holding.ts, packages/blue-sdk-viem/src/fetch/Holding.ts, packages/blue-sdk/src/addresses.ts, packages/blue-sdk/src/chain.ts, packages/blue-sdk/test/e2e/Market.test.ts, packages/bundler-sdk-viem/src/BundlerAction.ts, packages/bundler-sdk-viem/src/operations.ts, packages/liquidation-sdk-viem/src/addresses.ts, packages/migration-sdk-viem/src/config.ts, packages/migration-sdk-viem/src/fetchers/aaveV2/aaveV2.fetchers.ts, packages/simulation-sdk/src/errors.ts, packages/simulation-sdk/src/handlers/erc20/transfer2.ts
=> feat(chains): add all low support chains

package.json, packages/bundler-sdk-ethers/src/BundlerAction.ts, packages/bundler-sdk-viem/src/ActionBundle.ts, packages/bundler-sdk-viem/src/BundlerAction.ts, packages/bundler-sdk-viem/src/actions.ts, packages/bundler-sdk-viem/src/bundle.ts, packages/bundler-sdk-viem/src/index.ts, packages/bundler-sdk-viem/src/types/actions.ts, packages/bundler-sdk-viem/test/helpers.ts, packages/bundler-sdk-viem/test/populateBundle.test.ts, packages/bundler-sdk-viem/test/sharedLiquidity.test.ts, packages/migration-sdk-viem/src/MigrationBundle.ts, packages/migration-sdk-viem/src/index.ts, packages/migration-sdk-viem/src/positions/supply/MigratableSupplyPosition.ts, packages/migration-sdk-viem/src/positions/supply/aaveV2.supply.ts, packages/migration-sdk-viem/src/positions/supply/aaveV3.supply.ts, packages/migration-sdk-viem/src/positions/supply/aaveV3Optimizer.supply.ts, packages/migration-sdk-viem/src/positions/supply/compoundV2.supply.ts, packages/migration-sdk-viem/src/positions/supply/compoundV3.supply.ts, packages/migration-sdk-viem/src/types/actions.ts
=> feat(bundler): add setupBundle util

packages/blue-sdk/src/addresses.ts, packages/blue-sdk/src/chain.ts, packages/liquidation-sdk-viem/src/addresses.ts
=> feat(addresses): add batch2 deployment

packages/morpho-ts/README.md, packages/morpho-ts/src/format/format/format.ts, packages/morpho-ts/test/format.test.ts
=> feat(formatter): Add trailingZero() method

packages/liquidation-sdk-viem/src/addresses.ts
Added mainnet mEdge and mainnet mMEV asset
- https://docs.midas.app/resources/smart-contracts-addresses#medge-smart-contracts
As asked by midas:
=> feat(midas): adding mMEV and mEdge asset

package.json, packages/blue-sdk-viem/src/fetch/Position.ts, packages/blue-sdk-viem/test/PreLiquidationPosition.test.ts, packages/blue-sdk/src/errors.ts, packages/blue-sdk/src/position/Position.ts, packages/blue-sdk/src/position/PreLiquidationPosition.ts, packages/blue-sdk/src/preLiquidation.ts, packages/blue-sdk/test/unit/PreLiquidationPosition.test.ts
=> feat(pre-liquidation-params): add registry

packages/blue-sdk-wagmi/src/hooks/useHolding.ts, packages/blue-sdk-wagmi/src/hooks/useHoldings.ts, packages/blue-sdk-wagmi/src/hooks/useMarket.ts, packages/blue-sdk-wagmi/src/hooks/useMarkets.ts, packages/blue-sdk-wagmi/src/hooks/usePosition.ts, packages/blue-sdk-wagmi/src/hooks/usePositions.ts, packages/blue-sdk-wagmi/src/hooks/useToken.ts, packages/blue-sdk-wagmi/src/hooks/useTokens.ts, packages/blue-sdk-wagmi/src/hooks/useUser.ts, packages/blue-sdk-wagmi/src/hooks/useUsers.ts, packages/blue-sdk-wagmi/src/hooks/useVault.ts, packages/blue-sdk-wagmi/src/hooks/useVaultMarketConfig.ts, packages/blue-sdk-wagmi/src/hooks/useVaultMarketConfigs.ts, packages/blue-sdk-wagmi/src/hooks/useVaultUser.ts, packages/blue-sdk-wagmi/src/hooks/useVaultUsers.ts, packages/blue-sdk-wagmi/src/hooks/useVaults.ts
=> fix(wagmi): use stale time or default to infinity when block number defined

packages/bundler-sdk-viem/src/BundlerAction.ts, packages/bundler-sdk-viem/src/actions.ts, packages/bundler-sdk-viem/src/types/actions.ts, packages/simulation-sdk/src/operations.ts
=> feat(operation): add skipRevert

packages/blue-sdk/src/addresses.ts, packages/blue-sdk/src/chain.ts, packages/liquidation-sdk-viem/src/addresses.ts
Sibling PR to https://github.com/morpho-org/deployments/pull/84
=> fix(addresses): add plume mainnet

.github/workflows/test.yml
Temporarily disabling cache due to anvil issue
=> fix(tests): disable cache

packages/blue-sdk/src/preLiquidation.ts
- Add missing lltv key
- Fix lltv key value
- Uniformize number formatting
=> fix: preliquidation params values

packages/blue-sdk/src/market/Market.ts
This PR in itself is a breaking change, but the short lifetime of the feature vs the complexity cost of it makes it worth to drop right now (there's no real use case for it as of today)
=> fix(market): remove useless rate method

packages/bundler-sdk-viem/src/types/operations.ts, packages/simulation-sdk/src/errors.ts, packages/simulation-sdk/src/handlers/blue/buyDebt.ts, packages/simulation-sdk/src/handlers/blue/index.ts, packages/simulation-sdk/src/handlers/dispatchers.ts, packages/simulation-sdk/src/handlers/erc20/index.ts, packages/simulation-sdk/src/handlers/paraswap/buy.ts, packages/simulation-sdk/src/handlers/paraswap/index.ts, packages/simulation-sdk/src/handlers/paraswap/sell.ts, packages/simulation-sdk/src/operations.ts, packages/simulation-sdk/test/handlers/blue/buyDebt.test.ts, packages/simulation-sdk/test/handlers/paraswap/buy.test.ts, packages/simulation-sdk/test/handlers/paraswap/sell.test.ts
=> feat(simulation): add buy/sell/buyDebt operations

packages/blue-sdk/src/addresses.ts
The purpose of this PR is to add the unwrapped token mapping for the polygon chain
⚠️ This PR is targeting the `next` branch
=> feat(blue-sdk): added unwrapped native tokens

.github/workflows/test.yml, packages/bundler-sdk-viem/src/actions.ts
=> fix(bundler-sdk-viem): fix slippage usage

packages/blue-sdk/src/chain.ts
=> fix(chain): update katana explorer

packages/blue-sdk/src/addresses.ts
- add unichain paraswapAdapter address to the registry
=> feat(addresses): add unichain paraswapAdapter address to the registry

audits/2025-06-26-morpho-sdks-cantinacode.pdf
=> chore(audit): add cantina code report

packages/bundler-sdk-viem/src/actions.ts
- Change minSharePrice calculation  to match with on-chain formula
=> fix(actions): change minSharePrice calculation from mulDivUp to mulDivDown

packages/simulation-sdk/src/helpers/paraswap.ts
=> fix(paraswap): update augustus v6.2 abi

packages/blue-sdk/src/vault/Vault.ts
The rationale for not sharing the same naming convention than with Market is that:
1. `getAvgApy` is confusing for a vault: average over allocations or average over time? In our case both while `getApy` only average over allocations
2. most of the time a consumer of the apy of a vault is interested in the experience apy. If they want sophisticated analysis, they can compute the end borrow rate equivalent APY themselves
=> fix(vault): update apy method to use market avg supply apy

packages/bundler-sdk-viem/src/errors.ts, packages/bundler-sdk-viem/src/operations.ts, packages/bundler-sdk-viem/test/populateBundle.test.ts, packages/bundler-sdk-viem/test/sharedLiquidity.test.ts, packages/migration-sdk-viem/test/e2e/blue/borrow.test.ts
=> feat(skims): add sytemic skims to bundle

packages/morpho-ts/src/utils.ts
=> fix(morpho-ts): update keys return type

packages/blue-sdk/src/chain.ts
- update Katana explorer URL instead blockscout
=> fix(chain): update Katana explorer URL

packages/blue-sdk/src/addresses.ts, packages/blue-sdk/src/chain.ts, packages/liquidation-sdk-viem/src/addresses.ts
Add chain configuration for Sei.
=> sei chain config

packages/blue-api-sdk/src/types.ts
Bump types to add Vault V2 types.
=> feat(api-sdk): bump types
